### ISSUE TITLE
Internal Error on 1.12.1 

### ISSUE THREAD

**Issue by sensorware** [zabszk/TerrainClaim#2]
I am getting "An internal error occurred while attempting to perform this command" when I type "/terrain block"

Here is the console output 
=====================================
q2u issued server command: /terrain block
[23:29:34 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'terrain' in plugin TerrainClaim v1.2.5
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[gbinvl_minecraft_spigot_1_12_1.jar:git-Spigot-edd0396-2a927e8]
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[gbinvl_minecraft_spigot_1_12_1.jar:git-Spigot-edd0396-2a927e8]
at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:641) ~[gbinvl_minecraft_spigot_1_12_1.jar:git-Spigot-edd0396-2a927e8]
at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1386) [gbinvl_minecraft_spigot_1_12_1.jar:git-Spigot-edd0396-2a927e8]
at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1221) [gbinvl_minecraft_spigot_1_12_1.jar:git-Spigot-edd0396-2a927e8]
at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [gbinvl_minecraft_spigot_1_12_1.jar:git-Spigot-edd0396-2a927e8]
at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [gbinvl_minecraft_spigot_1_12_1.jar:git-Spigot-edd0396-2a927e8]
at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [gbinvl_minecraft_spigot_1_12_1.jar:git-Spigot-edd0396-2a927e8]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_45-internal]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_45-internal]
at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [gbinvl_minecraft_spigot_1_12_1.jar:git-Spigot-edd0396-2a927e8]
at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748) [gbinvl_minecraft_spigot_1_12_1.jar:git-Spigot-edd0396-2a927e8]
at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [gbinvl_minecraft_spigot_1_12_1.jar:git-Spigot-edd0396-2a927e8]
at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [gbinvl_minecraft_spigot_1_12_1.jar:git-Spigot-edd0396-2a927e8]
at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [gbinvl_minecraft_spigot_1_12_1.jar:git-Spigot-edd0396-2a927e8]
at java.lang.Thread.run(Thread.java:745) [?:1.8.0_45-internal]
Caused by: java.lang.NullPointerException
at org.bukkit.inventory.ItemStack.‹init›(ItemStack.java:68) ~[gbinvl_minecraft_spigot_1_12_1.jar:git-Spigot-edd0396-2a927e8]
at net.zabszk.terrain.Functions.getTerrainBlock(Functions.java:337) ~[?:?]
at net.zabszk.terrain.Main.onCommand(Main.java:515) ~[?:?]
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[gbinvl_minecraft_spigot_1_12_1.jar:git-Spigot-edd0396-2a927e8]
... 15 more

**Comment by sensorware** [comment]
Part of the config file was missing.  Copied the config file from here.  And all is working :)

**Comment by zabszk** [comment]
I was just building spigot 1.12.1 to test it out :D.

Have fun with my plugin.
